//Enum to differentiate types of board spaces
enum SpaceType {
    GO, PROPERTY, COMMUNITY_CHEST, CHANCE, JAIL, RAILROAD, FREE_PARKING,
    ELECTRIC_COMPANY, WATER_WORKS, LUXURY_TAX, INCOME_TAX, GOTO_JAIL;
}